"""행정안전부 지방행정 인허가정보 Python 클라이언트."""

from __future__ import annotations

from .catalogs import (
    get_file_download,
    get_incremental_openapi_endpoint,
    get_openapi_service,
    get_response_field,
    list_file_downloads,
    list_incremental_openapi_endpoints,
    list_openapi_endpoints,
    list_openapi_services,
    list_response_fields,
)
from .client import AsyncMoisClient, MoisClient
from .db import (
    Base,
    BatchSyncLog,
    PlaceCategorySummary,
    PlaceDetail,
    PlaceMaster,
    PlaceRecord,
    PlaceServiceSummary,
    PlaceStatsSummary,
    build_place_models,
    bulk_upsert_places,
    compact_json_dumps,
    create_sqlite_schema,
    infer_domain_category,
    load_spatialite_extension,
    record_to_place_record,
    refresh_spatial_geometries,
    refresh_sqlite_derived_tables,
    upsert_place,
    upsert_places,
)
from .debug import DebugRun, jsonable, redact_sensitive
from .exceptions import (
    MoisAuthError,
    MoisCatalogError,
    MoisError,
    MoisParseError,
    MoisRequestError,
    MoisServerError,
)
from .files import (
    AsyncLocalDataFileClient,
    LocalDataFileClient,
    iter_records_from_binary,
    iter_records_from_bytes,
    iter_records_from_text,
    load_records_from_bytes,
    load_records_from_text,
)
from .fixtures import save_debug_fixture, save_fixture, slugify
from .geocoding import (
    AddressGeocoder,
    AddressGeocodingProbe,
    AddressGeocodingValidationResult,
    GeocodingCandidate,
    validate_address_geocoding_probe,
    validate_address_geocoding_probe_async,
)
from .models import (
    BusinessStatusCategory,
    Condition,
    ConditionOperator,
    Coordinate,
    CoordinateReferenceSystem,
    FileDownload,
    FileDownloadKind,
    IncrementalOpenApiEndpoint,
    KatecPoint,
    LocalDataRecord,
    LocalDataRow,
    ManagementNumber,
    MoisResponse,
    OpenApiEndpoint,
    OpenApiItem,
    OpenApiKind,
    OpenApiService,
    ResponseField,
    ServiceSlug,
    StationCoordinates,
    SyncKind,
    Wgs84Point,
)
from .parser import parse_openapi_payload, parse_openapi_response, parse_openapi_text
from .processor import process_openapi_response

PROVIDER_NAME = "python-krmois-api"

__all__ = [
    "PROVIDER_NAME",
    "AsyncLocalDataFileClient",
    "AsyncMoisClient",
    "AddressGeocoder",
    "AddressGeocodingProbe",
    "AddressGeocodingValidationResult",
    "BusinessStatusCategory",
    "Condition",
    "ConditionOperator",
    "Coordinate",
    "CoordinateReferenceSystem",
    "DebugRun",
    "FileDownload",
    "FileDownloadKind",
    "GeocodingCandidate",
    "IncrementalOpenApiEndpoint",
    "KatecPoint",
    "LocalDataRow",
    "LocalDataFileClient",
    "LocalDataRecord",
    "ManagementNumber",
    "MoisAuthError",
    "MoisCatalogError",
    "MoisClient",
    "MoisError",
    "MoisParseError",
    "MoisRequestError",
    "MoisResponse",
    "MoisServerError",
    "OpenApiEndpoint",
    "OpenApiKind",
    "OpenApiItem",
    "OpenApiService",
    "PlaceDetail",
    "PlaceCategorySummary",
    "PlaceMaster",
    "PlaceRecord",
    "PlaceServiceSummary",
    "PlaceStatsSummary",
    "ResponseField",
    "ServiceSlug",
    "StationCoordinates",
    "SyncKind",
    "Wgs84Point",
    "Base",
    "BatchSyncLog",
    "bulk_upsert_places",
    "build_place_models",
    "compact_json_dumps",
    "create_sqlite_schema",
    "get_file_download",
    "get_incremental_openapi_endpoint",
    "get_openapi_service",
    "get_response_field",
    "infer_domain_category",
    "load_spatialite_extension",
    "list_file_downloads",
    "list_incremental_openapi_endpoints",
    "list_openapi_endpoints",
    "list_openapi_services",
    "list_response_fields",
    "iter_records_from_binary",
    "iter_records_from_bytes",
    "iter_records_from_text",
    "jsonable",
    "load_records_from_bytes",
    "load_records_from_text",
    "parse_openapi_payload",
    "parse_openapi_response",
    "parse_openapi_text",
    "process_openapi_response",
    "record_to_place_record",
    "refresh_sqlite_derived_tables",
    "refresh_spatial_geometries",
    "redact_sensitive",
    "save_debug_fixture",
    "save_fixture",
    "slugify",
    "upsert_place",
    "upsert_places",
    "validate_address_geocoding_probe",
    "validate_address_geocoding_probe_async",
]
