"""행정안전부 지방행정 인허가정보 Python 클라이언트."""

from __future__ import annotations

from .catalogs import (
    get_file_download,
    get_incremental_openapi_endpoint,
    get_openapi_service,
    get_response_field,
    list_file_downloads,
    list_incremental_openapi_endpoints,
    list_openapi_endpoints,
    list_openapi_services,
    list_response_fields,
)
from .client import MoisClient
from .db import (
    Base,
    BatchSyncLog,
    PlaceDetail,
    PlaceMaster,
    PlaceRecord,
    build_place_models,
    create_postgis_schema,
    infer_domain_category,
    record_to_place_record,
    upsert_place,
    upsert_places,
)
from .exceptions import (
    MoisAuthError,
    MoisCatalogError,
    MoisError,
    MoisParseError,
    MoisRequestError,
    MoisServerError,
)
from .files import (
    LocalDataFileClient,
    iter_records_from_binary,
    iter_records_from_bytes,
    iter_records_from_text,
    load_records_from_bytes,
    load_records_from_text,
)
from .models import (
    BusinessStatusCategory,
    Condition,
    ConditionOperator,
    Coordinate,
    CoordinateReferenceSystem,
    FileDownload,
    FileDownloadKind,
    IncrementalOpenApiEndpoint,
    KatecPoint,
    LocalDataRecord,
    LocalDataRow,
    ManagementNumber,
    MoisResponse,
    OpenApiEndpoint,
    OpenApiItem,
    OpenApiKind,
    OpenApiService,
    ResponseField,
    ServiceSlug,
    StationCoordinates,
    SyncKind,
    Wgs84Point,
)

__all__ = [
    "BusinessStatusCategory",
    "Condition",
    "ConditionOperator",
    "Coordinate",
    "CoordinateReferenceSystem",
    "FileDownload",
    "FileDownloadKind",
    "IncrementalOpenApiEndpoint",
    "KatecPoint",
    "LocalDataRow",
    "LocalDataFileClient",
    "LocalDataRecord",
    "ManagementNumber",
    "MoisAuthError",
    "MoisCatalogError",
    "MoisClient",
    "MoisError",
    "MoisParseError",
    "MoisRequestError",
    "MoisResponse",
    "MoisServerError",
    "OpenApiEndpoint",
    "OpenApiKind",
    "OpenApiItem",
    "OpenApiService",
    "PlaceDetail",
    "PlaceMaster",
    "PlaceRecord",
    "ResponseField",
    "ServiceSlug",
    "StationCoordinates",
    "SyncKind",
    "Wgs84Point",
    "Base",
    "BatchSyncLog",
    "build_place_models",
    "create_postgis_schema",
    "get_file_download",
    "get_incremental_openapi_endpoint",
    "get_openapi_service",
    "get_response_field",
    "infer_domain_category",
    "list_file_downloads",
    "list_incremental_openapi_endpoints",
    "list_openapi_endpoints",
    "list_openapi_services",
    "list_response_fields",
    "iter_records_from_binary",
    "iter_records_from_bytes",
    "iter_records_from_text",
    "load_records_from_bytes",
    "load_records_from_text",
    "record_to_place_record",
    "upsert_place",
    "upsert_places",
]
